version: '3.1'
services:

  db:
    image: postgres:16.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      #POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password

  web:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "90:8069"
      - "8072:8072" #live chat
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      #POSTGRES_PASSWORD: odoo
      POSTGRES_PASSWORD_FILE: /run/secrets/postgresql_password
    secrets:
      - postgresql_password
    #entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf --dev all"

# volumes:
#   postgres-data:
#   odoo-web-data:
#   odoo-17_db-data:
#     external: true
#   odoo-17_odoo-web-data:
#     external: true

secrets:
  postgresql_password:
    file: odoo_pg_pass